### PR TITLE
fix dbg call gate 64 support (info gdt long mode)

### PR DESCRIPTION
**Pull request by therealdreg**
Now dbg (**info gdt**) works as expected when it process a call gate 64 bit descriptor on GDT (long mode x86_64):

call_gate_64_support_gdt_long_mode

Before this PR: the dbg interprets a call gate 64 bit descriptor on GDT as a **32 bit call gate**. So, printed info is not complete :-(

Btw, call gate 64 descriptor sizeof() (long mode) is 16, so 2 entries :D

intel1

intel2

IMO, In a near future **we should redesign** dbg info gdt command. The current code prints wrong info on long mode because no 16-byte descriptor support yet. 

This PR is a temporal patch to support **ONLY ONE** of them: **a call gate 64 bit descriptor**.

For example, current dbg interprets a **64-bit TSS** as a **32-Bit TSS** wtf.

wtf

@stlintel can you merge this please? I need fix this bug ASAP because I will publish a paper using this feature :D, and you know, people want use official Bochs repo :D

Dev+Tested on: 
- Windows x64 Host (x64 Bochs.exe) with a x64 Linux Guest

### CODE REVIEW

**Comment by stlintel** [comment]
Why don't you do exactly the same as was done for bx_dbg_info_idt_command ?
The same thing exactly could be done for both bx_dbg_info_gdt_command and bx_dbg_info_ldt_command and will support all cases and not just call gate

**Comment by therealdreg** [comment]
> Why don't you do exactly the same as was done for bx_dbg_info_idt_command ? The same thing exactly could be done for both bx_dbg_info_gdt_command and bx_dbg_info_ldt_command and will support all cases and not just call gate

mmm, because for me makes sense the current code (read 8 each loop, and when the type is a 64-bit descriptor read 16). No?

**Comment by stlintel** [comment]
Smth like this:
```
#if BX_SUPPORT_X86_64
  if (BX_CPU(dbg_cpu)->long_mode()) {
    dbg_printf("Global Descriptor Table (base=0x" FMT_ADDRX ", limit=%d):\n", gdtr.base, gdtr.limit);
    for (unsigned n = from - from % 2; n<=to; n+=2) {
      Bit8u entry[16];
      if (16*n + 15 > idtr.limit) break;
      if (bx_dbg_read_linear(dbg_cpu, idtr.base + 16*n, 16, entry)) {
        dbg_printf("IDT[0x%02x]=", n);

        Bit32u lo1 = (entry[3]  << 24) | (entry[2]  << 16) | (entry[1]  << 8) | (entry[0]);
        Bit32u hi1 = (entry[7]  << 24) | (entry[6]  << 16) | (entry[5]  << 8) | (entry[4]);
        Bit32u lo2 = (entry[11] << 24) | (entry[10] << 16) | (entry[9]  << 8) | (entry[8]);
        Bit32u hi2 = (entry[15] << 24) | (entry[14] << 16) | (entry[13] << 8) | (entry[12]);

        bx_dbg_print_descriptor64(lo1, hi1, lo2, hi2);
      }
      else {
        dbg_printf("error: GDTR+16*%d points to invalid linear address 0x" FMT_ADDRX "\n", n, idtr.base);
      }
    }
  }
  else
#endif
  {

```

**Comment by stlintel** [comment]
If I remember correctly (might be wrong) - descriptors in long mode are all 16-byte or not supported anymore.
There is no way to jump out of long mode with change of the descriptor

**Comment by stlintel** [comment]
for (unsigned n = from - from % 2; n<=to; n+=2) { 

Might be here I am not sure. Only odd descriptor indexes matter or any ?

**Comment by therealdreg** [comment]
> Smth like this:
> 
> ```
> #if BX_SUPPORT_X86_64
>   if (BX_CPU(dbg_cpu)->long_mode()) {
>     dbg_printf("Global Descriptor Table (base=0x" FMT_ADDRX ", limit=%d):\n", gdtr.base, gdtr.limit);
>     for (unsigned n = from - from % 2; n<=to; n+=2) {
>       Bit8u entry[16];
>       if (16*n + 15 > idtr.limit) break;
>       if (bx_dbg_read_linear(dbg_cpu, idtr.base + 16*n, 16, entry)) {
>         dbg_printf("IDT[0x%02x]=", n);
> 
>         Bit32u lo1 = (entry[3]  << 24) | (entry[2]  << 16) | (entry[1]  << 8) | (entry[0]);
>         Bit32u hi1 = (entry[7]  << 24) | (entry[6]  << 16) | (entry[5]  << 8) | (entry[4]);
>         Bit32u lo2 = (entry[11] << 24) | (entry[10] << 16) | (entry[9]  << 8) | (entry[8]);
>         Bit32u hi2 = (entry[15] << 24) | (entry[14] << 16) | (entry[13] << 8) | (entry[12]);
> 
>         bx_dbg_print_descriptor64(lo1, hi1, lo2, hi2);
>       }
>       else {
>         dbg_printf("error: GDTR+16*%d points to invalid linear address 0x" FMT_ADDRX "\n", n, idtr.base);
>       }
>     }
>   }
>   else
> #endif
>   {
> ```

in GDT can be a 8 bit type. and do you NOT know what a mount of data its necessary, for me makes sense something like:

Read 8, if type is 64 bit, read other 8 and calls 64 version and n++ n++
Read 8, if type is 8 bit, calls current version and n++

**Comment by stlintel** [comment]
The code in LDT suggests to print everything at 8-byte step
So if odd index contains 16-byte descriptor it will printed as 64-byte descriptor and them 'undef' on next entry with even index
I believe this is good way to print it.
Could be improved by looking on the descriptor type or better adding a return value from bx_dbg_print_descriptor64 which will tell if 16-byte or 8-byte. But might be not necessary for your needs.

**Comment by therealdreg** [comment]
> The code in LDT suggests to print everything at 8-byte step So if odd index contains 16-byte descriptor it will printed as 64-byte descriptor and them 'undef' on next entry with even index I believe this is good way to print it. Could be improved by looking on the descriptor type or better adding a return value from bx_dbg_print_descriptor64 which will tell if 16-byte or 8-byte. But might be not necessary for your needs.

Yep, I want avoid read 16 each time because what if there is a half 64 bit descriptor at the end of GDT (and PAGE)? this sound stupid but its possible xD

GDT
.....
....
HALF 64 BIT DESCRIPTOR <- GDT END  PAGE END
* NO PAGE HERE

**Comment by stlintel** [comment]
Tried to make my one PR but have no way to validate it
https://github.com/stlintel/Bochs/pull/32
Try it

**Comment by therealdreg** [comment]
> Tried to make my one PR but have no way to validate it #32 Try it

I see a possible out of bounds, let me think in this one day :-)

**Comment by stlintel** [comment]
Half 64-bit descriptor at the end is an error and it will be printed as an error:

        dbg_printf("error: GDTR+16*%d points to invalid linear address 0x" FMT_ADDRX "\n", n, gdtr.base);

Or, if gdtr.limit boundary it will just ignored

      if (16*n + 15 > gdtr.limit) break;

**Comment by stlintel** [comment]
> > Tried to make my one PR but have no way to validate it #32 Try it
> 
> I see a possible out of bounds, let me think in this one day :-)

It was 2-minutes craft, might be could be improved :)
Where do you see "out of bounds" ?

**Comment by therealdreg** [comment]
> Half 64-bit descriptor at the end is an error and it will be printed as an error:
> 
> ```
>     dbg_printf("error: GDTR+16*%d points to invalid linear address 0x" FMT_ADDRX "\n", n, gdtr.base);
> ```
> 
> Or, if gdtr.limit boundary it will just ignored
> 
> ```
>   if (16*n + 15 > gdtr.limit) break;
> ```

In GDT can be a mix of different entries, and you are reading 16x16 and I think this is wrong, your read-memory-code works fine with:

entry_type_8
entry_type_8
entry_type_8
entry_type_8

But what if:

entry_type_16
entry_type_8

**Comment by stlintel** [comment]
In the PR #32 every memory read is 16-byte but loop step is 8.
No entry will be missed.
16-byte entries will be printed as 2 - one good and one bogus.

entry 1: entry_type_16
entry 3: entry_type_8  <= this is bogus in long mode, not supported gate type

Will print:
entry 1: Call gate 64
entry 2: undef
entry 3: undef

**Comment by therealdreg** [comment]
> In the PR #32 every memory read is 16-byte but loop step is 8. No entry will be missed. 16-byte entries will be printed as 2 - one good and one bogus.
> 
> entry 1: entry_type_16 entry 3: entry_type_8 <= there are no valid 8-byte types in long mode
> 
> Will print: entry 1: Call gate 64 entry 2: undef entry 3: undef

look this:

0008 CodeER Bas=00000000 Lim=ffffffff DPL=0 P  A  G BIG AVL=0 L=0
0010 CodeER Bas=00000000 Lim=ffffffff DPL=0 P  A  G     AVL=0 L=1
0018 DataRW Bas=00000000 Lim=ffffffff DPL=0 P  A  G BIG AVL=0 L=0
0020 CodeER Bas=00000000 Lim=ffffffff DPL=3 P  A  G BIG AVL=0 L=0
0028 DataRW Bas=00000000 Lim=ffffffff DPL=3 P  A  G BIG AVL=0 L=0
0030 CodeER Bas=00000000 Lim=ffffffff DPL=3 P  A  G     AVL=0 L=1
0040 Tss64B Bas=fffffe0000003000 Lim=00004087 DPL=0 P  B         AVL=0 R=0
004c .....

As you can see it exist in long mode 8-type entries!! xD

**Comment by stlintel** [comment]
Pushed a change to PR #32 
How about now ?

**Comment by therealdreg** [comment]
> Pushed a change to PR #32 How about now ?

Yep, this looks fine, thx for your time :D I can test it in 9 hours if you want

**Comment by stlintel** [comment]
Yes, please test and notify if fine.
Will be merged once you confirm :)

**Comment by therealdreg** [comment]
> Yes, please test and notify if fine. Will be merged once you confirm :)

Yep I will test this with something like:

...
CALL GATE 64 to CS_1
CS_1
CALL GATE 64 to CS_2
CALL GATE 64 to CS_1
CS_2
...

And just execute some call far to different call gates to check all entries are well-formed and after that check the info gdt :D

**Comment by therealdreg** [comment]
#33 should be the correct thing! :-D

**Pull request closed without merging**
